import asyncio
import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import anthropic
from fpdf import FPDF

from deception.prompts.report_generator import MITRE_MAPPING_PROMPT

logger = logging.getLogger(__name__)

REPORT_DIR = Path(os.getenv("REPORT_OUTPUT_DIR", "/app/reports"))
REPORT_DIR.mkdir(parents=True, exist_ok=True)

FOOTER_TEXT = "GENERATED BY PROJECT MIRAGE — SIMULATED ENVIRONMENT — FOR TRAINING PURPOSES"


class MiragePDF(FPDF):
    def header(self) -> None:
        pass

    def footer(self) -> None:
        self.set_y(-12)
        self.set_font("Courier", size=7)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, FOOTER_TEXT, align="C")


async def _call_llm_for_mitre(client: anthropic.AsyncAnthropic, transcript_text: str) -> dict:
    try:
        result = await asyncio.wait_for(
            client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=2000,
                system=MITRE_MAPPING_PROMPT,
                messages=[{"role": "user", "content": f"Session transcript:\n{transcript_text}"}],
            ),
            timeout=30.0,
        )
        raw = result.content[0].text.strip()
        return json.loads(raw)
    except Exception as exc:
        logger.error("MITRE LLM call failed: %s", exc)
        return {
            "inferred_objective": "Unknown",
            "confidence": "LOW",
            "tactics": [],
            "techniques": [],
            "executive_summary": "Analysis unavailable due to processing error.",
            "recommended_countermeasures": ["Review session logs manually."],
        }


def _build_transcript_text(session: Any) -> str:
    lines = []
    for entry in session.transcript:
        role = entry.get("role", "unknown").upper()
        content = entry.get("content", "")[:300]
        lines.append(f"[{role}]: {content}")
    return "\n".join(lines) if lines else "No transcript available."


def _build_timeline_rows(session: Any) -> list[list[str]]:
    rows = []
    for i, entry in enumerate(session.transcript):
        role = entry.get("role", "?")
        content = entry.get("content", "")[:80]
        score = session.anomaly_scores[i // 2] if i // 2 < len(session.anomaly_scores) else 0.0
        rows.append([str(i + 1), role, content, f"{score:.3f}"])
    return rows


def _generate_pdf(session: Any, analysis: dict) -> Path:
    pdf = MiragePDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Cover page
    pdf.add_page()
    pdf.set_fill_color(20, 20, 20)
    pdf.rect(0, 0, 210, 297, "F")

    pdf.set_font("Courier", "B", 10)
    pdf.set_text_color(239, 68, 68)
    pdf.set_y(20)
    pdf.cell(0, 8, "[ TOP SECRET — SIMULATED ENVIRONMENT ]", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(15)
    pdf.set_font("Courier", "B", 20)
    pdf.set_text_color(34, 211, 238)
    pdf.cell(0, 12, "PROJECT MIRAGE", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Courier", "B", 14)
    pdf.set_text_color(200, 200, 200)
    pdf.cell(0, 10, "THREAT INTELLIGENCE FORENSIC REPORT", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(20)
    pdf.set_font("Courier", size=10)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, f"Session ID:  {session.session_id}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Source IP:   {session.source_ip}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Generated:   {datetime.now(timezone.utc).isoformat()}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Confidence:  {analysis.get('confidence', 'LOW')}", align="C", new_x="LMARGIN", new_y="NEXT")

    # Executive Summary
    pdf.add_page()
    pdf.set_fill_color(255, 255, 255)
    pdf.set_font("Courier", "B", 13)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "EXECUTIVE SUMMARY", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Courier", size=10)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 6, analysis.get("executive_summary", "N/A"))
    pdf.ln(4)
    pdf.set_font("Courier", "B", 10)
    pdf.cell(40, 6, "Inferred Objective:")
    pdf.set_font("Courier", size=10)
    pdf.cell(0, 6, analysis.get("inferred_objective", "N/A"), new_x="LMARGIN", new_y="NEXT")

    # Session Timeline
    pdf.ln(6)
    pdf.set_font("Courier", "B", 13)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "SESSION TIMELINE", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Courier", "B", 8)
    pdf.set_fill_color(220, 220, 220)
    for col, width in [("#", 10), ("Role", 20), ("Content Preview", 120), ("Score", 20)]:
        pdf.cell(width, 7, col, border=1, fill=True)
    pdf.ln()
    pdf.set_font("Courier", size=8)
    for row in _build_timeline_rows(session):
        for val, width in zip(row, [10, 20, 120, 20]):
            pdf.cell(width, 6, val[:60], border=1)
        pdf.ln()

    # MITRE ATT&CK Mapping
    pdf.ln(6)
    pdf.set_font("Courier", "B", 13)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "MITRE ATT&CK MAPPING", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Courier", "B", 8)
    pdf.set_fill_color(220, 220, 220)
    for col, width in [("Tactic ID", 25), ("Tactic Name", 55), ("Evidence", 90)]:
        pdf.cell(width, 7, col, border=1, fill=True)
    pdf.ln()
    pdf.set_font("Courier", size=8)
    for tactic in analysis.get("tactics", []):
        pdf.cell(25, 6, tactic.get("id", ""), border=1)
        pdf.cell(55, 6, tactic.get("name", "")[:30], border=1)
        pdf.cell(90, 6, tactic.get("evidence", "")[:60], border=1)
        pdf.ln()

    pdf.ln(4)
    pdf.set_font("Courier", "B", 10)
    pdf.cell(0, 7, "Techniques", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Courier", "B", 8)
    pdf.set_fill_color(220, 220, 220)
    for col, width in [("Tech ID", 30), ("Name", 60), ("Evidence", 80)]:
        pdf.cell(width, 7, col, border=1, fill=True)
    pdf.ln()
    pdf.set_font("Courier", size=8)
    for tech in analysis.get("techniques", []):
        pdf.cell(30, 6, tech.get("id", ""), border=1)
        pdf.cell(60, 6, tech.get("name", "")[:35], border=1)
        pdf.cell(80, 6, tech.get("evidence", "")[:50], border=1)
        pdf.ln()

    # Deception Transcript
    pdf.add_page()
    pdf.set_font("Courier", "B", 13)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "DECEPTION TRANSCRIPT", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Courier", size=9)
    for i, entry in enumerate(session.transcript, 1):
        role = entry.get("role", "?").upper()
        content = entry.get("content", "")[:400]
        pdf.set_text_color(180, 30, 30) if role == "USER" else pdf.set_text_color(30, 130, 30)
        pdf.set_font("Courier", "B", 9)
        pdf.cell(0, 6, f"{i}. [{role}]", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Courier", size=8)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(0, 5, content)
        pdf.ln(2)

    # Countermeasures
    pdf.add_page()
    pdf.set_font("Courier", "B", 13)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "RECOMMENDED COUNTERMEASURES", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Courier", size=10)
    for i, measure in enumerate(analysis.get("recommended_countermeasures", []), 1):
        pdf.multi_cell(0, 6, f"{i}. {measure}")
        pdf.ln(2)

    filename = f"mirage_report_{session.session_id[:12]}_{int(datetime.now().timestamp())}.pdf"
    output_path = REPORT_DIR / filename
    pdf.output(str(output_path))
    return output_path


async def generate_forensic_report(session: Any) -> Path:
    client = anthropic.AsyncAnthropic()
    transcript_text = _build_transcript_text(session)
    analysis = await _call_llm_for_mitre(client, transcript_text)
    return _generate_pdf(session, analysis)
